#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations



// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_WEATHER_CURRENT_CONDITIONS = 0,
    FLOW_GLOBAL_VARIABLE_WEATHER_DATE = 1,
    FLOW_GLOBAL_VARIABLE_DAILY_STEPS = 2,
    FLOW_GLOBAL_VARIABLE_DAILY_STEP_PCT = 3,
    FLOW_GLOBAL_VARIABLE_HOUR_LABEL_1 = 4,
    FLOW_GLOBAL_VARIABLE_HOUR_LABEL_2 = 5,
    FLOW_GLOBAL_VARIABLE_HOUR_LABEL_3 = 6,
    FLOW_GLOBAL_VARIABLE_HOUR_LABEL_4 = 7,
    FLOW_GLOBAL_VARIABLE_HOUR_LABEL_5 = 8,
    FLOW_GLOBAL_VARIABLE_HOUR_LABEL_6 = 9,
    FLOW_GLOBAL_VARIABLE_HOUR_LABEL_7 = 10,
    FLOW_GLOBAL_VARIABLE_HOUR_AMPM_1 = 11,
    FLOW_GLOBAL_VARIABLE_HOUR_AMPM_2 = 12,
    FLOW_GLOBAL_VARIABLE_HOUR_AMPM_3 = 13,
    FLOW_GLOBAL_VARIABLE_HOUR_AMPM_4 = 14,
    FLOW_GLOBAL_VARIABLE_HOUR_AMPM_5 = 15,
    FLOW_GLOBAL_VARIABLE_HOUR_AMPM_6 = 16,
    FLOW_GLOBAL_VARIABLE_HOUR_AMPM_7 = 17,
    FLOW_GLOBAL_VARIABLE_HOUR_TEMP_0 = 18,
    FLOW_GLOBAL_VARIABLE_HOUR_TEMP_1 = 19,
    FLOW_GLOBAL_VARIABLE_HOUR_TEMP_2 = 20,
    FLOW_GLOBAL_VARIABLE_HOUR_TEMP_3 = 21,
    FLOW_GLOBAL_VARIABLE_HOUR_TEMP_4 = 22,
    FLOW_GLOBAL_VARIABLE_HOUR_TEMP_5 = 23,
    FLOW_GLOBAL_VARIABLE_HOUR_TEMP_6 = 24,
    FLOW_GLOBAL_VARIABLE_HOUR_TEMP_7 = 25,
    FLOW_GLOBAL_VARIABLE_HOUR_ICON_0 = 26,
    FLOW_GLOBAL_VARIABLE_HOUR_ICON_1 = 27,
    FLOW_GLOBAL_VARIABLE_HOUR_ICON_2 = 28,
    FLOW_GLOBAL_VARIABLE_HOUR_ICON_3 = 29,
    FLOW_GLOBAL_VARIABLE_HOUR_ICON_4 = 30,
    FLOW_GLOBAL_VARIABLE_HOUR_ICON_5 = 31,
    FLOW_GLOBAL_VARIABLE_HOUR_ICON_6 = 32,
    FLOW_GLOBAL_VARIABLE_HOUR_ICON_7 = 33,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_0 = 34,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_1 = 35,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_2 = 36,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_3 = 37,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_4 = 38,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_5 = 39,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_6 = 40,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_7 = 41,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_8 = 42,
    FLOW_GLOBAL_VARIABLE_DAY_FORECAST_9 = 43,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_0 = 44,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_1 = 45,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_2 = 46,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_3 = 47,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_4 = 48,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_5 = 49,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_6 = 50,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_7 = 51,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_8 = 52,
    FLOW_GLOBAL_VARIABLE_HIGH_TEMP_FORECAST_9 = 53,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_0 = 54,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_1 = 55,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_2 = 56,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_3 = 57,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_4 = 58,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_5 = 59,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_6 = 60,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_7 = 61,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_8 = 62,
    FLOW_GLOBAL_VARIABLE_LOW_TEMP_FORECAST_9 = 63,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_0 = 64,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_1 = 65,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_2 = 66,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_3 = 67,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_4 = 68,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_5 = 69,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_6 = 70,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_7 = 71,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_8 = 72,
    FLOW_GLOBAL_VARIABLE_ICON_FORECAST_9 = 73,
    FLOW_GLOBAL_VARIABLE_CALCULATOR_HISTORY = 74,
    FLOW_GLOBAL_VARIABLE_CALCULATOR_INPUT = 75,
    FLOW_GLOBAL_VARIABLE_ALARM_HOUR = 76,
    FLOW_GLOBAL_VARIABLE_ALARM_MINUTE = 77,
    FLOW_GLOBAL_VARIABLE_ALARM_AM_PM = 78,
    FLOW_GLOBAL_VARIABLE_ALARM_ACTIVE = 79,
    FLOW_GLOBAL_VARIABLE_ALARM_SOUND = 80,
    FLOW_GLOBAL_VARIABLE_ALARM_PLAYING = 81,
    FLOW_GLOBAL_VARIABLE_ALARM_SNOOZE = 82,
    FLOW_GLOBAL_VARIABLE_ALARM_NEXT_ALARM = 83,
    FLOW_GLOBAL_VARIABLE_SNOOZE_TIME_PERIOD = 84,
    FLOW_GLOBAL_VARIABLE_TIMER_RUNNING = 85,
    FLOW_GLOBAL_VARIABLE_TIMER_HOUR = 86,
    FLOW_GLOBAL_VARIABLE_TIMER_MINUTE = 87,
    FLOW_GLOBAL_VARIABLE_TIMER_SECOND = 88,
    FLOW_GLOBAL_VARIABLE_TIMER_PLAYING = 89,
    FLOW_GLOBAL_VARIABLE_TIMER_SOUND = 90,
    FLOW_GLOBAL_VARIABLE_TIMER_ARC_PERCENT = 91,
    FLOW_GLOBAL_VARIABLE_TIMER_ARC_TOTAL_SECS = 92,
    FLOW_GLOBAL_VARIABLE_STOPWATCH_RUNNING = 93,
    FLOW_GLOBAL_VARIABLE_STOPWATCH_START_TIME = 94,
    FLOW_GLOBAL_VARIABLE_STOPWATCH_ELAPSED = 95,
    FLOW_GLOBAL_VARIABLE_WEATHER_LOCATIONS = 96,
    FLOW_GLOBAL_VARIABLE_WEATHER_LOCATION_DIGIT1 = 97,
    FLOW_GLOBAL_VARIABLE_WEATHER_LOCATION_DIGIT2 = 98,
    FLOW_GLOBAL_VARIABLE_WEATHER_LOCATION_DIGIT3 = 99,
    FLOW_GLOBAL_VARIABLE_WEATHER_LOCATION_DIGIT4 = 100,
    FLOW_GLOBAL_VARIABLE_WEATHER_LOCATION_DIGIT5 = 101,
    FLOW_GLOBAL_VARIABLE_WEATHER_TEMPERATURE = 102,
    FLOW_GLOBAL_VARIABLE_WEATHER_HUMIDITY_PERCENTAGE = 103,
    FLOW_GLOBAL_VARIABLE_WEATHER_WIND_SPEED = 104,
    FLOW_GLOBAL_VARIABLE_WEATHER_MIN_MAX = 105,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_COUNT = 106,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_ICON = 107,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_TITLE = 108,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_MESSAGE = 109,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_DATETIME = 110,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_VISIBLE = 111,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_HAS_PREV = 112,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_HAS_NEXT = 113,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_HAS_POSITIVE = 114,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_HAS_NEGATIVE = 115,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_UNVIEWED = 116,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_IMPORTANT = 117,
    FLOW_GLOBAL_VARIABLE_INCOMING_CALL_NAME = 118,
    FLOW_GLOBAL_VARIABLE_INCOMING_CALL_NUMBER = 119,
    FLOW_GLOBAL_VARIABLE_INCOMING_CALL_UID = 120,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_POSITIVE_LABEL = 121,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_NEGATIVE_LABEL = 122,
    FLOW_GLOBAL_VARIABLE_QUICK_NOTIFICATION_TITLE = 123,
    FLOW_GLOBAL_VARIABLE_QUICK_NOTIFICATION_MESSAGE = 124,
    FLOW_GLOBAL_VARIABLE_QUICK_NOTIFICATION_ICON = 125,
    FLOW_GLOBAL_VARIABLE_QUICK_NOTIFICATION_IMPORTANT = 126,
    FLOW_GLOBAL_VARIABLE_WIFI_AVAILABLE_SELECTION = 127,
    FLOW_GLOBAL_VARIABLE_WIFI_AVAILABLE_LIST = 128,
    FLOW_GLOBAL_VARIABLE_WIFI_CREDS_IS_OPEN = 129,
    FLOW_GLOBAL_VARIABLE_WIFI_CREDS_IS_SAVED = 130,
    FLOW_GLOBAL_VARIABLE_WIFI_CREDS_SSID = 131,
    FLOW_GLOBAL_VARIABLE_WIFI_CREDS_PASSWORD = 132,
    FLOW_GLOBAL_VARIABLE_WIFI_CREDS_JOIN_SUCCESS = 133,
    FLOW_GLOBAL_VARIABLE_MEDIA_TITLE = 134,
    FLOW_GLOBAL_VARIABLE_MEDIA_ARTIST = 135,
    FLOW_GLOBAL_VARIABLE_MEDIA_ALBUM = 136,
    FLOW_GLOBAL_VARIABLE_MEDIA_DURATION = 137,
    FLOW_GLOBAL_VARIABLE_MEDIA_IS_PLAYING = 138,
    FLOW_GLOBAL_VARIABLE_MEDIA_APP = 139,
    FLOW_GLOBAL_VARIABLE_MEDIA_ELAPSED_TIME = 140,
    FLOW_GLOBAL_VARIABLE_ALARM_NEXT_ALARM_STRING = 141,
    FLOW_GLOBAL_VARIABLE_ALARM_TRIGGERED = 142,
    FLOW_GLOBAL_VARIABLE_MEDIA_VOLUME = 143,
    FLOW_GLOBAL_VARIABLE_MEDIA_TIME_REMAINING = 144,
    FLOW_GLOBAL_VARIABLE_MEDIA_PROGRESS = 145,
    FLOW_GLOBAL_VARIABLE_STOPWATCH_ELAPSED_STRING = 146,
    FLOW_GLOBAL_VARIABLE_CALENDAR_DATE = 147,
    FLOW_GLOBAL_VARIABLE_CALENDAR_PICKER_HIDDEN = 148,
    FLOW_GLOBAL_VARIABLE_CALENDAR_PICKER_YEAR = 149,
    FLOW_GLOBAL_VARIABLE_CALENDAR_PICKER_MONTH = 150,
    FLOW_GLOBAL_VARIABLE_CALENDAR_PICKER_DAY = 151,
    FLOW_GLOBAL_VARIABLE_CALENDAR_PICKER_DAY_OPTIONS = 152,
    FLOW_GLOBAL_VARIABLE_CALENDAR_NO_EVENTS_SHOWN = 153,
    FLOW_GLOBAL_VARIABLE_CALENDAR_SHOW_SPINNER = 154,
    FLOW_GLOBAL_VARIABLE_ACTIVE_CALL_VISIBLE = 155,
    FLOW_GLOBAL_VARIABLE_ACTIVE_CALL_DURATION = 156
};

// Native global variables

extern int32_t get_var_time_secs();
extern void set_var_time_secs(int32_t value);
extern const char *get_var_time_min();
extern void set_var_time_min(const char *value);
extern const char *get_var_time_hour();
extern void set_var_time_hour(const char *value);
extern const char *get_var_date_day_of_week();
extern void set_var_date_day_of_week(const char *value);
extern const char *get_var_date_day_of_month();
extern void set_var_date_day_of_month(const char *value);
extern const char *get_var_date_year();
extern void set_var_date_year(const char *value);
extern const char *get_var_battery_charge_pct();
extern void set_var_battery_charge_pct(const char *value);
extern bool get_var_is_charging();
extern void set_var_is_charging(bool value);
extern const char *get_var_weather_city();
extern void set_var_weather_city(const char *value);
extern const char *get_var_weather_icon_large();
extern void set_var_weather_icon_large(const char *value);
extern const char *get_var_weather_icon_small();
extern void set_var_weather_icon_small(const char *value);
extern int32_t get_var_weather_locations_selected_index();
extern void set_var_weather_locations_selected_index(int32_t value);
extern bool get_var_wifi_connected();
extern void set_var_wifi_connected(bool value);
extern const char *get_var_wifi_ssid();
extern void set_var_wifi_ssid(const char *value);
extern int32_t get_var_wifi_signal_strength();
extern void set_var_wifi_signal_strength(int32_t value);
extern bool get_var_weather_needs_reload();
extern void set_var_weather_needs_reload(bool value);
extern int32_t get_var_settings_brightness();
extern void set_var_settings_brightness(int32_t value);
extern int32_t get_var_settings_volume();
extern void set_var_settings_volume(int32_t value);
extern int32_t get_var_settings_daily_steps_goal();
extern void set_var_settings_daily_steps_goal(int32_t value);


#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/